apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-hello-world
  template:
    metadata:
      labels:
        app: spring-boot-hello-world
    spec:
      containers:
      - name: app
        image: <your-container-registry>/spring-boot-hello-world:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 45
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-hello-world-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /actuator/health
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: spring-boot-hello-world
