version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing Docker and AWS CLI..."
      - curl -fsSL https://get.docker.com -o get-docker.sh
      - sh get-docker.sh
      - usermod -aG docker $USER
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install

  pre_build:
    commands:
      - echo "Installing Maven..."
      - echo "Logging in to ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 654654607707.dkr.ecr.us-east-1.amazonaws.com
      - export REPOSITORY_URI=654654607707.dkr.ecr.us-east-1.amazonaws.com/app1
      - export COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - export IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo "Building the Spring Boot application..."
      - mvn clean install
      - echo "Building Docker image..."
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - echo "Build completed successfully!"
      - printf "Image URI: %s:%s" $REPOSITORY_URI $IMAGE_TAG

artifacts:
  files:
    - target/*.jar
