apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-hello-world
  template:
    metadata:
      labels:
        app: spring-boot-hello-world
    spec:
      containers:
      - name: spring-boot-container
        image: your-account-id.dkr.ecr.your-region.amazonaws.com/spring-boot-hello-world:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
