apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb" # or adjust as per your AWS Load Balancer Controller if using ALB
spec:
  type: LoadBalancer
  selector:
    app: spring-boot-hello-world
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
